language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --configuration phpunit.xml
  - vendor/bin/phpcs --standard=PSR2 -p --report=full --report-checkstyle=build/logs/checkstyle.xml src/ tests/

cache:
  directories:
    - $HOME/.composer/cache/files
